# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v5.2.0
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: null
domains_test: null
gitlab_url: ""
odoo_dbfilter: ^prod_doodba
odoo_initial_lang: en_US
odoo_listdb: true
odoo_oci_image: ""
odoo_proxy: traefik
odoo_version: 16.0
paths_without_crawlers:
  - /web
  - /website/info
postgres_cidr_whitelist: null
postgres_dbname: prod_doodba
postgres_exposed: true
postgres_exposed_port: 5432
postgres_username: vaiarii
postgres_version: "15"
project_author: Vaiarii TEPA
project_license: no_license
project_name: Doodba first project
smtp_default_from: vaiarii@invitu.com
smtp_relay_host: ""
